// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.3
// LVGL version: 8.2.0
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////
lv_obj_t *ui_Screen1;
lv_obj_t *ui_Label2;
lv_obj_t *ui_Label1;
lv_obj_t *ui_Label4;
lv_obj_t *ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
//#if LV_COLOR_DEPTH != 16
//#error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
//#endif
//#if LV_COLOR_16_SWAP !=1
//#error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
//#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////
void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL,NULL);

    ui_Label2 = lv_label_create(ui_Screen1,NULL);
    lv_obj_set_width(ui_Label2, 100);  /// 1
    lv_obj_set_height(ui_Label2, 100);   /// 1
    lv_obj_set_x(ui_Label2, 93);
    lv_obj_set_y(ui_Label2, 33);
    //lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);

    ui_Label1 = lv_label_create(ui_Screen1,NULL);
    lv_obj_set_width(ui_Label1, 100);  /// 1
    lv_obj_set_height(ui_Label1, 100);   /// 1
    lv_obj_set_x(ui_Label1, 47);
    lv_obj_set_y(ui_Label1, 44);
    //lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "666666");

    ui_Label4 = lv_label_create(ui_Screen1,NULL);
    lv_obj_set_width(ui_Label4, 100);  /// 1
    lv_obj_set_height(ui_Label4, 100);   /// 1
    lv_obj_set_x(ui_Label4, 6);
    lv_obj_set_y(ui_Label4, 6);
    //lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);

}

void ui_init(void)
{
    rt_err_t ret = RT_EOK;
    ret = littlevgl2rtt_init("lcd");
    if(ret != RT_EOK)
    {
        return ret;
    }

    lv_disp_t *dispp = lv_disp_get_default();
    ui_Screen1_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL,NULL);
    lv_disp_load_scr(ui_Screen1);
}
